### ISSUE TITLE
'_msize_base': redefinition causes several projects to fail compilation

### ISSUE THREAD

**Issue by minneelyyyy** [mastercomfig/team-comtress-2#623] opened 2022-07-13 21:24 UTC
### Description
Visual Studio complains about a redefinition of a Windows function '_msize_base' inside of the file memoverride.cpp. This causes 26 the programs to fail compilation.

### Checklist
- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.

- [ ] This issue occurs on the latest vanilla TF2 update.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. This occurs when following the steps found on the wiki for compiling on [Windows](https://github.com/mastercomfig/team-comtress-2/wiki/Windows-Build-Instructions)

### Screenshots
![image](https://user-images.githubusercontent.com/79120883/178838308-fd247d25-8071-4a28-8e83-b22eec05e00b.png)

#### Client Settings

- *Server or client:* Both
- *Operating system:* Windows 10
- *Team Comtress version:* master
- *Custom content:* none
- *Launch options:* none
#### Driver Version

- *Graphics driver:* NVIDIA 516.59
- *DirectX level:* none
#### Hardware Specs

- *CPU model:* i7-7700
- *GPU model:* NVIDIA GTX 1060
- *RAM amount:* 16GB
- *TF2 install location:*
- *TC2 install location:* SSD
- *TC2 installation method:* Compiled from source, failed

**Comment by mastercoms** [comment] 2022-07-13 21:57
dupe of #621

**Closed by mastercoms** 2022-07-13 21:57 UTC
Labels: bug, tc2, needs triage

**Comment by minneelyyyy** [comment] 2022-07-13 22:03
so... windows likes to change its sdk up on developers... cool
