### ISSUE TITLE
ominous looking engineer on main menu

### ISSUE THREAD

**Issue by MasterZitron** [mastercomfig/team-comtress-2#397] opened 2020-10-03 18:19 UTC
### Description

Red Engineer threatening my life with a shotgun while A posing

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.

- [ ] This issue occurs on the latest vanilla TF2 update.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. This is the first time I opened the program, on a (kinda) fresh TF2 install,
2. I opened start_tf2 and this happened
3. ??

### Screenshots

![image](https://user-images.githubusercontent.com/32692021/94998876-8121c880-058b-11eb-92c2-dbe457652a6a.png)

[video](https://streamable.com/5pll3r)

#### Client Settings

- *Server or client*: Client
- *Operating system:* Windows 10
- *Team Comtress version:* 0.13
- *Custom content:* None
- *Launch options:* None

**Comment by maxwellhupig** [comment] 2020-10-04 08:05
oh no

**Comment by Yttrium-tYcLief** [comment] 2020-10-04 09:37
duplicate of #397

**Closed by Yttrium-tYcLief** 2020-10-04 09:37 UTC
Labels: bug, tc2

**Comment by micwoj92** [comment] 2020-10-04 09:57
@Yttrium-tYcLief ????????

**Comment by Melonenyoshi** [comment] 2020-10-04 17:06
funny to me
