### ISSUE TITLE
[Request] Multiple minor improvements that could be applied to the game?

### ISSUE THREAD

**Issue by some-username-here1** [mastercomfig/team-comtress-2#168] opened 2020-09-16 06:15 UTC
**Is your feature request related to a problem? Please describe.**
There's multiple issues that has persisted between here and tf2 and I was wondering if they could be fixed or improved upon, including a few features that Gmod has.

1. for `tf_bot_taunt_by_chance`, when the player gets killed, **both** the killer and assistant should taunt if the chance for the bots to taunt happens.
2. again, for the same command from above, but for the Dead Ringer, as the command doesn't work properly with this weapon. So when a player fakes their death, the bot that killed the player should taunt as normal (including the assistant, if applicable).
3. The ability to change fps_max while in-game, as Garry's Mod was somehow able to do it.
4. Add "Borderless Window" to Display mode under Video Options, as Gmod has been able to.
5. When applying changes after changing the "Silence the audio while the game window is in the background." option, whatever the sound engine was playing gets stopped immediately. The Linux version of TF2 (or maybe any Source game) was somehow able to get around this, so would it be possible in the Windows version?
6. On ctf_2fooooooooooort, for some odd reason, the function that is used for the launchpads in front of both forts sends the player flying backwards instead of forward towards the bridge.
7. When looking at water a certain way, the reflection would end up glitching out and could end up persisting onto the next map, even when it shouldn't be.

![image](https://user-images.githubusercontent.com/34193156/93296993-02b8de80-f7b6-11ea-856a-89ebc5fa5043.png)

8. There's an issue with this waterfall on a map I was testing, with the first image showing what's happening, and the second image is what should happen normally.

![image](https://user-images.githubusercontent.com/34193156/93295655-23336980-f7b3-11ea-8285-6d0ede259220.png)
![image](https://user-images.githubusercontent.com/34193156/93296356-a6a18a80-f7b4-11ea-92c2-2454b048757c.png)

9. When the Valve intro is playing, is it possible for the game to continue loading in the background as normal? So once it's done, the main menu shows up right then and there.

**Comment by micwoj92** [comment] 2020-09-16 06:19
It would be better if you split these issues in separate tickets for easier managing.

**Comment by some-username-here1** [comment] 2020-09-16 06:20
oh alright, I'll try to do that

**Comment by some-username-here1** [comment] 2020-09-16 06:23
What about putting issues 1 and 2 together? Along with 3 and 4 going together

**Comment by micwoj92** [comment] 2020-09-16 06:25
If you think that the problem has same root cause then in my opinion yes.

**Comment by Yttrium-tYcLief** [comment] 2020-09-16 07:28
I'm going to close this main issue. Open new ones for individual issues whenever needed.

**Closed by Yttrium-tYcLief** 2020-09-16 07:28 UTC
