### ISSUE TITLE
Bug with recording

### ISSUE THREAD

**Issue by daze725** [mastercomfig/team-comtress-2#303] opened 2020-09-22 18:19 UTC
When you try to record on a tf2 server (all servers even custom) You will not be able to record so you would have to use a different software.

- [ ] None of the open *or* closed issues document this problem.
- [ yes] This is a bug, not a new idea.
- [ ] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ yes] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [yes ] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

**Comment by mastercoms** [comment] 2020-09-22 20:10
Recording with what?

**Comment by Yttrium-tYcLief** [comment] 2020-09-22 21:57
He likely means recording a demo, in which case this is a duplicate of #191. 

I'm going to close this as a duplicate; if this isn't a duplicate, it can be reopened once a better description is given.

**Closed by Yttrium-tYcLief** 2020-09-22 21:57 UTC
Labels: bug, needs triage, tf2
