### ISSUE TITLE
Bots getting stuck in comp maps

### ISSUE THREAD

**Issue by MysticTutor** [mastercomfig/team-comtress-2#286] opened 2020-09-20 23:53 UTC
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1.

### Setup Details
- *Server or client:* 
- *Operating system:* 
- *Team Comtress version:* 
- *Custom content:* 
- *Launch options:* 

- *Graphics driver:* 
- *DirectX level:* 

### Performance Details

- *GPU model:* 
- *CPU model:* 
- *RAM amount:* 
- *TF2 installed on:* 
- *TC2 installed on:* 
- *TC2 installation method:*

**Comment by wgetJane** [comment] 2020-09-21 01:03
why did you leave the description and reproduction sections empty

**Comment by Yttrium-tYcLief** [comment] 2020-09-21 02:53
map issues are definitely out of scope unless it's a problem with the actual AI system, but this sounds like navmeshes, yeah.

**Closed by Yttrium-tYcLief** 2020-09-21 02:53 UTC
Labels: bug, needs triage, tf2

**Comment by MysticTutor** [comment] 2020-09-22 22:48
I didn't. But I did accadently put the description between the <-- --> not realizing that would make them not show and now all of the bugs and suggestions I submitted have been closed.

why did you leave the description and reproduction sections empty



-----Original Message-----

**Comment by Yttrium-tYcLief** [comment] 2020-09-23 01:16
As a collaborator I can view your raw comment. The only content you put inside of comment brackets was "Play any comp map with a bot", from what I can see.

Regardless, I didn't close this because of submission issues, just because the bug, while definitely being problematic, is 100% out of scope currently.
