### ISSUE TITLE
[MVM] Giant Robots are using human body sizes

### ISSUE THREAD

**Issue by DrCactusTF2** [mastercomfig/team-comtress-2#261] opened 2020-09-19 20:50 UTC
### Description
MVM Giants in TC2 are using the same body proportions as their common counterparts

### Checklist

- [X] None of the open *or* closed issues document this problem.
- [ ] This is a bug, not a new idea.
- [X] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [X] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [X] This issue occurs when using no custom content.
- [X] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [X] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. Play any wave with a giant
2. Stand/taunt next to them for height reference

### Screenshots
https://steamuserimages-a.akamaihd.net/ugc/1638704307077383998/75BD3A0B31A45A10F01C73C19BCC47357688EF8C/

**Comment by maximsmol** [comment] 2020-09-19 20:58
I don't think I understand this issue. What is the intended behavior?

**Comment by Yttrium-tYcLief** [comment] 2020-09-19 21:06
> I don't think I understand this issue. What is the intended behavior?

Giants have scaled-up bodies, but normal sized heads. They don't use separate models; they simply use the original models with a scale factor (of like 3x) applied to their root bone, and then a scale on bip_head to bring it back down to normal size. My guess is we somehow broke that in TC2.

**Comment by DrCactusTF2** [comment] 2020-09-19 21:20
For reference, this is how big they're supposed to be in live TF2
https://steamuserimages-a.akamaihd.net/ugc/1638704307080206910/884F6FEB9815CDACAFB7419D84A0794573F1770A/

**Comment by Yttrium-tYcLief** [comment] 2020-09-27 18:30
oh this was fixed in 5974bce my bad

**Closed by Yttrium-tYcLief** 2020-09-27 18:30 UTC
Labels: bug, mvm, tc2
