### ISSUE TITLE
[MVM] Tough Break Universal Switch speed buff breaks robots

### ISSUE THREAD

**Issue by ghost** [mastercomfig/team-comtress-2#224] opened 2020-09-18 21:34 UTC
Ever since Gun Mettle's universal weapon switch buff (0.67 to 0.50), Bots with items such as Bonk! Atomic Punch or Soldier Banners will often attempt to switch to it, but will be stuck in a endless loop of switch as the AI calculates the old speed, causing the robot to never attack. Most noticeable with giant Banners on Rottenburg or giant bonks on Mannhattan.

**Comment by maximsmol** [comment] 2020-09-21 17:20
Duplicate of #258

**Closed by maximsmol** 2020-09-21 17:20 UTC
Labels: bug, needs triage, tf2
