### ISSUE TITLE
[MVM] Burn Time does not work

### ISSUE THREAD

**Issue by ghost** [mastercomfig/team-comtress-2#223] opened 2020-09-18 20:53 UTC
Ever since the jungle inferno update changed the way afterburn works, the "Burn Time" upgrade has been completely broken and does not add any extra time to your afterburn.

I think this is because the burn time upgrade uses attributes that were made for the original flames

**Comment by maximsmol** [comment] 2020-09-21 17:23
Duplicate of #259

**Closed by maximsmol** 2020-09-21 17:23 UTC
Labels: bug, duplicate, mvm, tf2
