### ISSUE TITLE
T-posing bots

### ISSUE THREAD

**Issue by kittyron** [mastercomfig/team-comtress-2#645] opened 2023-03-10 20:11 UTC
### Description

Bots in offline practice are T-posing
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.

- [ ] This issue occurs on the latest vanilla TF2 update.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Click find a game in main menu
2. Select training
3. Then offline practice
4. Select any mode, map and amount of bots (happens on all modes and maps I checked, Bot difficulty doesn't matter as well)
5. Click start practice
6. See T-posing bots

### Screenshots

![Untitled](https://user-images.githubusercontent.com/127242677/224417556-d18fffb7-117f-4c27-81ff-bde4e254c35e.png)

#### Client Settings

- *Server or client: Client* 
- *Operating system: Windows 11* 
- *Team Comtress version: 1.2.1* 
- *Custom content: None* 
- *Launch options None:* 
#### Driver Version

- *Graphics driver:* 
- *DirectX level:* 
#### Hardware Specs

- *CPU model:* 
- *GPU model:* 
- *RAM amount:* 
- *TF2 install location:* 
- *TC2 install location:* 
- *TC2 installation method:*

**Comment by mastercoms** [comment] 2023-03-10 20:18
how did you start the map

**Comment by kittyron** [comment] 2023-03-10 20:33
> how did you start the map


https://user-images.githubusercontent.com/127242677/224422904-7c81667c-4a69-4124-b7fc-804318da1ce0.mp4

**Comment by treacherousfiend** [comment] 2023-03-10 20:41
Reproduced on 1.2.0 as well, TF bots in general seem to be broken no matter how they're spawned? I tried your method, `tf_bot_add` and `bot` and all of them were broken. It seems that for some reason the bots do not have any valid weapons
Something I did notice was that engis are mostly unaffected? they seem to spawn with the toolbox out and can place a building, but then can't swap off of it to the wrench and kind of get stuck because they want to upgrade their buildings.
Spies also wander around with their sapper out but thats it

**Comment by treacherousfiend** [comment] 2023-03-10 20:46
I did some more testing, this isn't a bot issue, stock weapons in general are completely bugged right now? If you have a stock weapon in your loadout you will just not be given it.

**Comment by kittyron** [comment] 2023-03-10 21:22
I just noticed there are 2 the same stock weapons. One is loaded from loadout from vanilla game and the other one is from team comtress. Not working one is from team comtress. (you can hear that I can't use pistol)

https://user-images.githubusercontent.com/127242677/224430729-9a703e51-3a38-430e-bc37-5b47356314c8.mp4

**Comment by kittyron** [comment] 2023-03-10 21:23
Also spy has PDA instead of sapper.

https://user-images.githubusercontent.com/127242677/224430986-4ff9bec8-fb16-49f7-8d59-f58eb69a98a0.mp4

**Comment by kittyron** [comment] 2023-03-10 21:24
The only weapon that seems to be working is PDA.

**Comment by treacherousfiend** [comment] 2023-03-10 21:26
The pistol that works here is one that has a skin on it on the live game. A few of us looked into this issue and it seems to be a regression with how the game initializes the inventory system on local servers, so any "economy" items (i.e. cosmetics, weapons aside from stock, weapons with skins on them) load fine, but the base stock weapons do not. Hopefully will be fixed soon.

**Comment by kittyron** [comment] 2023-03-10 21:27
> The pistol that works here is one that has a skin on it on the live game. A few of us looked into this issue and it seems to be a regression with how the game initializes the inventory system on local servers, so any "economy" items (i.e. cosmetics, weapons aside from stock, weapons with skins on them) load fine, but the base stock weapons do not. Hopefully will be fixed soon.

Makes sense forgot that I had skins on these weapons

**Comment by ReplayCoding** [comment] 2023-03-10 21:28
Not sure if this is the proper fix, but GenerateBaseItems isn't called anywhere else in the code:
```patch
diff --git a/src/game/shared/tf/tf_item_inventory.cpp b/src/game/shared/tf/tf_item_inventory.cpp
index 6c3ee4a5..0e321f95 100644
--- a/src/game/shared/tf/tf_item_inventory.cpp
+++ b/src/game/shared/tf/tf_item_inventory.cpp
@@ -225,12 +225,7 @@ void CTFInventoryManager::PostInit( void )
 void CTFInventoryManager::InitializeInventory()
 {
 	BaseClass::InitializeInventory();
-#ifdef GAME_DLL
-	if ( engine->IsDedicatedServer() )
-#endif
-	{
-		GenerateBaseItems();
-	}
+	GenerateBaseItems();
 }
 
 //-----------------------------------------------------------------------------
```

**Closed as completed** 2023-03-11 18:05 UTC
Labels: bug, tc2, needs triage
