### ISSUE TITLE
[MVM] Giants do not resist Scorch Shot/Loose Canon knockback

### ISSUE THREAD

**Issue by ghost** [mastercomfig/team-comtress-2#222] opened 2020-09-18 20:51 UTC
Giants have an innate resistance to knockback from certain weapons like the Scorch Shot, Loose Canon and Force A Nature

In the Gun Mettle update, the Scorch Shot was changed, and this unintentionally affected how Giants are affected by said knockback.
This was then (sort of) fixed in the September 24, 2015 patch
"Fixed a push bug with The Scorch Shot and giant robots in Mann vs. Machine mode."
Although, this didn't entirely fix the issue, as you could still use it to stun giants, it was serviceable.

Then the Tough Break update released with the following change
"Consecutive Airblasts will no longer prevent enemies from air-strafing until they touch the ground "

This reverted the previous fix, while making the problem even worse than before, as you could now send giant robots flying with relative ease, and this also bypasses ubercharge

https://youtu.be/2pd0VF-PY7A
Video attached for reference

**Comment by maximsmol** [comment] 2020-09-21 17:23
Duplicate of #260

**Closed by maximsmol** 2020-09-21 17:23 UTC
Labels: bug, needs triage, tf2
