### ISSUE TITLE
Add a Comtress version indicator

### ISSUE THREAD

**Issue by GoodOldJack12** [mastercomfig/team-comtress-2#313] opened 2020-09-23 12:31 UTC
### Description
There should be a way to identify which *released* version of the patch is currently installed.
This should, in my opinion, be done with a simple text file in the root TF2 directory. Optionally a small text in the main menu.

This is useful to verify if a bug report isn't from an older version by accident.

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).
- [x] This is obviously an improvement, not something that people commonly disagree on.

- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [x] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Screenshots

N/A
### Alternatives

N/A

**Comment by agrastiOs** [comment] 2020-09-23 16:22
Possible versions of implementation: FILEVERSION/PRODUCT VERSION resource in the client executable, version info in HUD at main menu, .txt with version number in root directory

**Comment by Yttrium-tYcLief** [comment] 2020-09-23 19:05
Duplicate of #33

**Closed by Yttrium-tYcLief** 2020-09-23 19:05 UTC
Labels: enhancement, good first issue, tc2

**Comment by GoodOldJack12** [comment] 2020-09-23 20:49
I don't believe that this is a duplicate. 
While related, the other issues specifically asks for a *command*.
A command that can only be executed if the game actually runs properly.

This type of versioning would work without having to run the game.
If this suggestion were to merged with #33, that would be fair and acceptable, but it is not a duplicate.

**Comment by Yttrium-tYcLief** [comment] 2020-09-23 21:11
I'll expand #33 to cover this as well.
