### ISSUE TITLE
Sapper bug and class selection animation

### ISSUE THREAD

**Issue by condor00fr** [mastercomfig/team-comtress-2#244] opened 2020-09-19 10:19 UTC
The sappers used to fall off buildings when destroyed when the game released, not anymore, aparently due to a mistake in the code or a bug.
Also the class selection screen animations are kinda broken and don't play their sounds like in 2007 anymore.
fixing some of those would be cool.

**Comment by duh9406** [comment] 2020-09-19 11:20
I thought the devs remove the broken sapper model for performance purposes?

**Comment by condor00fr** [comment] 2020-09-19 11:37
I don't think so
I mean we still have gibs and all.
I remember somewhere having heard of it.

**Comment by Yttrium-tYcLief** [comment] 2020-09-19 12:45
>besides it woudn't hurt to see em back

That's irrelevant. If this was a design change/choice, and not a bug, it's outside of scope for this project.

I'll wait to hear back from someone more knowledgeable on whether this is a bug or not before closing it.

**Comment by agrastiOs** [comment] 2020-09-19 13:34
The sapper gibs used to provide ammo, they might have been removed for balance reasons too. I'm doubting it was an unintended removal, but maybe a look at the code of the sapper might provide insight if it's just broken or actually removed.

**Comment by agrastiOs** [comment] 2020-09-19 14:02
There has been a fix made for the choppy class animations by ficool2: https://steamcommunity.com/sharedfiles/filedetails/?id=2153744818

**Comment by Yttrium-tYcLief** [comment] 2020-09-19 16:52
> There has been a fix made for the choppy class animations by ficool2: https://steamcommunity.com/sharedfiles/filedetails/?id=2153744818

While this is a separate issue from the sapper one, and should be in its own issue, I'll briefly address it.

Looking at the description of that submission, it seems there are 4 key issues. I won't bother repeating them all here, but issue 1 has to do with the HUD elements themselves, which we are intentionally staying away from with this project. Issue 2 (sound) is a legitimate game code issue that we could address. Issue 3 is an animation issue with game assets, which we don't touch. Issue 4 is likely a code issue, but may or may not get fixed by Valve, and there unfortunately isn't enough information in that short description to tell us what's going on there.

**Comment by maximsmol** [comment] 2020-09-19 18:36
Animation changes are out of scope.
Sapper changes are too borderline for us to make a real decision on this.
Marking as "revisit" and closing.

**Closed by maximsmol** 2020-09-19 18:36 UTC
Labels: bug, revisit, tf2, wontfix
