### ISSUE TITLE
Pressing "N" while ingame causes severe rendering problems.

### ISSUE THREAD

**Issue by Zionner** [mastercomfig/team-comtress-2#285] opened 2020-09-20 23:34 UTC
### Description
Whenever I press "N", which according to my keyboard settings, is bound to "Take Steam Abuse Screenshot" severe rendering glitches occur. Both with the 3D geometry, and the UI.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. Enter 2Fort (I used map ctf_2fort)
2. Press "N".

Note: If this doesn't happen for you, check that your keybinding for "N" is the same as mine "Take Steam Abuse Screenshot".

### Screenshots
[Image](https://i.imgur.com/ARr5LCF.jpg)

### Setup Details
- *Server or client:* Client
- *Operating system:* Windows 10
- *Team Comtress version:* a360bec
- *Custom content:* None
- *Launch options:* Just tf2.bat

- *Graphics driver:* Nvidia 446.14
- *DirectX level:* 98

### Performance Details
- *GPU model:* NVIDIA GTX 2070 Super
- *CPU model:* Intel Core i7-4790k
- *RAM amount:* 16GB
- *TF2 installed on:* 
- *TC2 installed on:* Hybrid
- *TC2 installation method:* Advanced

**Comment by Yttrium-tYcLief** [comment] 2020-09-20 23:58
Duplicate of #246.

**Closed by Yttrium-tYcLief** 2020-09-20 23:58 UTC
Labels: bug, needs triage, tc2
