### ISSUE TITLE
DX12 support

### ISSUE THREAD

**Issue by kuletxcore** [mastercomfig/team-comtress-2#109] opened 2020-09-15 02:35 UTC
**Is your feature request related to a problem? Please describe.**
This is an Enhancement request, and is not related to any issues.
This suggestion should be **low in priority** *unless* adding DX12 support would increase FPS and reduce lag.

In adding DX12 support, you would also have support for DX10 and DX11.

**Describe the solution you'd like**
Add support for DirectX 12 and hopefully (just wishful thinking and will probably never happen,) DLSS and Ray-tracing for RTX-enabled graphics cards

**Describe alternatives you've considered**
Force the -DXLevel flag to a setting higher than it allows.

**Additional context**
Here is a link for a DX12-related repository you can integrate.
(I am unsure if this is DX12 Ultimate that uses DLSS or not)
https://github.com/microsoft/DirectXTK12

**Comment by treacherousfiend** [comment] 2020-09-15 02:38
sort of related repository
https://github.com/PazerOP/TF2Vulkan

Also, tf2 technically already has dx10 support, but its basically just dx9

**Comment by kuletxcore** [comment] 2020-09-15 02:42
> sort of related repository
> https://github.com/PazerOP/TF2Vulkan
> 
> Also, tf2 technically already has dx10 support, but its basically just dx9

Oh, neat! I'm gonna check it out soon!

**Comment by micwoj92** [comment] 2020-09-15 03:49
This is just #39 but worse.

**Comment by Yttrium-tYcLief** [comment] 2020-09-15 08:32
Duplicate of #39

**Closed by Yttrium-tYcLief** 2020-09-15 08:32 UTC
