### ISSUE TITLE
mat_phong & doing screenshots

### ISSUE THREAD

**Issue by twelvef1** [mastercomfig/team-comtress-2#357] opened 2020-09-27 18:12 UTC
### Checklist

- [ ] None of the open *or* closed issues document this problem.

- [ x ] This is a bug, not a new idea.
- [ x ] This is objectively a bug, and not something that people commonly disagree on.
- [  ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [  ] This issue occurs on the latest vanilla TF2 update.
- [  ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ x ] This issue occurs with DirectX level 100.
- [ x ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [ x ] This issue occurs when using no custom content.
- [  ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [  ] This issue occurs when using a listen server (using the `map` command ingame).
- [  ] This issue occurs when using a dedicated server.
- [  ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1.

### Screenshots

![20200927195022_1](https://user-images.githubusercontent.com/71983969/94372309-b5fdcd80-00fc-11eb-93d2-dea7fdaa9ceb.jpg)
![20200927195100_1](https://user-images.githubusercontent.com/71983969/94372310-b72efa80-00fc-11eb-821c-c09217e67f15.jpg)
![20200927195109_1](https://user-images.githubusercontent.com/71983969/94372311-b9915480-00fc-11eb-9847-65521b18d45d.jpg)
![20200927195007_1](https://user-images.githubusercontent.com/71983969/94372334-d7f75000-00fc-11eb-9519-f97631c457c0.jpg)

### Setup Details
- *CLIENT* 
- *Operating system: WIN7* 
- *Team Comtress version: 0.17* 
- *Custom content: none* 
- *Launch options: -novid -nojoy -nosteamcontroller -nohltv -particle_fallback 2 %* < nul* 

- *Graphics driver: 342.01* 
- *DirectX level: 100* 

### Performance Details

- *GPU model: GeForce GT 220* 
- *CPU model: Intel Pentium Dual-Core E5300 2.60GHz* 
- *RAM amount: 4GB* 
- *TF2 installed on: HDD* 
- *TC2 installed on: HDD* 
- *TC2 installation method: Basic*

**Comment by micwoj92** [comment] 2020-09-27 18:13
please fill checklist with x instead of yes/no

**Comment by twelvef1** [comment] 2020-09-27 18:27
> please fill checklist with x instead of yes/no

done

**Comment by Yttrium-tYcLief** [comment] 2020-09-27 18:31
duplicate of #246 and is unrelated to phong

**Closed by Yttrium-tYcLief** 2020-09-27 18:31 UTC
Labels: bug, needs triage, tc2
