### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by mastercoms** [mastercomfig/team-comtress-2#5] opened 2020-08-16 02:31 UTC
We need to identify the cause of some reported CTDs.

**Comment by IllinoisBois** [comment] 2020-08-24 05:10
The current build would immediately crash for me. After I restarted Steam, it booted once, where I was able to get to the inventory screen. The next moment I clicked, it crashed. After the one successful boot it did't work afterwards.

**Comment by wgetJane** [comment] 2020-08-24 05:16
@IllinoisBois that's most likely caused by the game trying to nag the player about the pyro vs heavy war
it should be fixed by https://github.com/mastercomfig/team-comtress-2/commit/dc400c0652b03e0c658ddaa6c021c4dc0d26a752

**Comment by IllinoisBois** [comment] 2020-08-24 05:20
@wgetJane After completely exiting Steam, I got the game to run without crashing though I cannot join into a private map. After opening Steam I am no longer able to run the game. Quite the paradox.

**Closed** 2020-08-25 20:20 UTC
