### ISSUE TITLE
cp_mountainlab can't be loaded

### ISSUE THREAD

**Issue by rcmaehl** [mastercomfig/team-comtress-2#502] opened 2020-11-04 20:54 UTC
### Description

Having a dedicated or listen server attempt to host cp_mountainlab crashes the server or client. I am unsure if this due to a corrupt map as it loads fine in TF2 but my version can be found here: [cp_mountainlab.zip](https://github.com/mastercomfig/team-comtress-2/files/5490437/cp_mountainlab.zip)
 
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.

- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. Launch a client or dedicated server
2. map cp_mountainlab

### Screenshots
No long output to console.log

#### Client Settings

- *Server or client:* YES
- *Operating system:* Windows 10 19041.572
- *Team Comtress version:* 0.3.1
- *Custom content:* mastercomfig ultra
- *Launch options:* start_tf2.bat
#### Driver Version

- *Graphics driver:* 20.4.2
- *DirectX level:* default
#### Hardware Specs

- *CPU model:* R7 1800X
- *GPU model:* RX480 8GB
- *RAM amount:* 32GB
- *TF2 install location:* SSD
- *TC2 install location:* SSD
- *TC2 installation method:* Basic

**Comment by treacherousfiend** [comment] 2020-11-04 21:22
Reproduced on the current release (0.3.1), but this is not reproducible on current master (213be2e)
I have no clue what would cause this bug, since to my knowledge the only difference between the two versions is weapon related code.

**Comment by agrastiOs** [comment] 2020-11-08 22:15
Closing, pending feedback. If anyone can confirm that they receive crashes on the current master, please report and the issue will be reopened.

**Closed by agrastiOs** 2020-11-08 22:15 UTC
Labels: bug, tc2

**Comment by rcmaehl** [comment] 2020-11-10 03:08
> Closing, pending feedback. If anyone can confirm that they receive crashes on the current master, please report and the issue will be reopened.

I'll try again during next release. ;)
