### ISSUE TITLE
[MVM] Huntsman bugs

### ISSUE THREAD

**Issue by ghost** [mastercomfig/team-comtress-2#227] opened 2020-09-18 21:51 UTC
The huntsman has a few notable bugs in Mann vs. Machine.
1. Damage is improperly rounded.
412 / 360 = 1,1444 = 14,44% <---- first Damage Upgrade
465 / 360 = 1,2916 = 29,16% <---- second Damage Upgrade
517 / 360 = 1,4361 = 43,61% <---- third Damage Upgrade
570 / 360 = 1,5833 = 58,33% <---- fourth Damage Upgrade
Max damage upgrade huntsman only increases the damage by 58.33% instead of the advertised 100%
2. Reload stability arc
Reload speed decreases the charge time needed to reach the max damage, but the arrow stability you get at max charge is unaffected, and you still need to wait for the stock huntsman charge time to get stable arrows
3. Penetration is completely broken on Huntsman
Huntsman actually suffers from buying projectile penetration, as penetration will cause the arrows to instantly break if you tap fire them, or fire them while ubered.
Pyro bots also cannot reflect non-penetration arrows, but can reflect penetration arrows just fine

**Comment by maximsmol** [comment] 2020-09-21 17:17
Duplicate of #255

**Closed by maximsmol** 2020-09-21 17:17 UTC
Labels: bug, duplicate, mvm, tf2
