### ISSUE TITLE
[MVM] Vaccinator Bubble Bugs

### ISSUE THREAD

**Issue by ghost** [mastercomfig/team-comtress-2#225] opened 2020-09-18 21:39 UTC
The Vaccinator suffers from 2 notable bugs in MVM.
The first is that reviving a player will sometimes cost 2 bubbles instead of the intended one bubble. This is is very inconsistent, and most likely a bug.
The second one is that Ubercharge duration has 0 effect on the Vaccinator's bubble charges. Even holding down all 4 charges has no effect on the duration.

**Comment by maximsmol** [comment] 2020-09-21 17:19
Duplicate of #257

**Closed by maximsmol** 2020-09-21 17:19 UTC
Labels: bug, mvm, tf2
