### ISSUE TITLE
[MVM] Repeatedly Tapping M1 will cause players to be revived faster than designed

### ISSUE THREAD

**Issue by ghost** [mastercomfig/team-comtress-2#226] opened 2020-09-18 21:43 UTC
When playing as a medic in MVM, repeatedly tapping a revive hologram will cause it to revive the player much faster than you are supposed to be able to. This is most noticeable with a max healing mastery quick fix.

**Comment by maximsmol** [comment] 2020-09-21 17:18
Duplicate of #256

**Closed by maximsmol** 2020-09-21 17:18 UTC
Labels: bug, duplicate, tf2
